### ISSUE TITLE
How to add custom text when killing?

### ISSUE THREAD

**Issue by LeoDemitori** [Estecka/mc-ALL-Death-Messages#8]
How to add custom text when a player is killed by a mob?
This is a very important function, it would be nice to create its own line in the lang file for each mob

**Comment by Estecka** [comment]
What sort of custom text ? I'm afraid this is out of scope for this mod. All-Death does not fundamentally changes how death messages are generated, it just makes those messages available to mobs other than players.

**Comment by LeoDemitori** [comment]
> Что за пользовательский текст? Боюсь, что это выходит за рамки этого мода. All-Death принципиально не меняет способ генерации сообщений о смерти, он просто делает эти сообщения доступными для других мобов, кроме игроков.


This is a logical continuation of the mod.
This functionality will be very useful for modpack developers.

**Example of text customization:**
**Event:** *player killed by enderman*
**The text that is broadcast to everyone on the server:** "The player was killed by **<entity>** because he looked into his eyes"

You can create variations for each mod so that the text is different for each death.

**my example config:**
create a small client version of the mod to place only a localization file there, which will contain lines about the death of the player from each creature.

**lang:**
- examplemod:example_mob1: "text"

or make an additional option in the config on the server:

> {
> "rule": [
> "minecraft:player"
> ],
> "custom_death_text": "The player was killed by **<entity>** because he looked into his eyes",
> },

**Comment by Estecka** [comment]
> This is a logical continuation of the mod.

I don't think it is in its current state. Neither of the config files are well suited to define this kind of messages, and nothing in the current codebase would help much with the programming. All-Death doesn't even know how to identify the fatal blow. (Kill rules actually evaluate **all** recent aggressors equally.)
If I wanted to work on such a feature right now, I might as well start from scratch and make it into a completely separate mod.

The mod [Girlbossed](https://modrinth.com/mod/girlbossed) seems to do exactly what you want. Their modrinth page is a bit outdated, but their github repo shows activity for a 1.20.1 version, so you might have some luck asking over there.

**Comment by LeoDemitori** [comment]
> > Это логическое продолжение мода.
> 
> Я не думаю, что он находится в нынешнем состоянии. Ни один из конфигурационных файлов не подходит для определения такого рода сообщений, и ничто в текущей кодовой базе не поможет в программировании. Все-Смерть даже не знает, как определить смертельный удар. (Правила убийства на самом деле оценивают **всех** недавних агрессоров одинаково.) Если бы я хотел работать над такой функцией прямо сейчас, я мог бы начать с нуля и сделать из нее совершенно отдельный мод.
> 
> Мод [Girlbossed,](https://modrinth.com/mod/girlbossed) кажется, делает именно то, что вы хотите. Их страница modrinth немного устарела, но их репозиторий github показывает активность для версии 1.20.1, так что вам может повезти, если вы спросите там.

Okay( Thx you!
